Add complexes page
VLanc/yard-frontend pull request #1
Opened 2017-06-16 13:33 UTC by VLanc

2017-06-16 18:41 UTC, imevro requested changes
Я уже говорил тебе про табы и идентацию внутри бади

2017-06-16 21:44 UTC, imevro requested changes
https://rawgit.com/VLanc/yard-frontend/develop/src/complexes.html

верстка поехала в карточках
нет паттерна на фоне
футер не как в макете

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +<title>Main</title>
тайтл поч уехал

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +  <div class = "banner">
мне кажется тут могут два во ро бья про лет еть

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +          <div class="col-lg-8 col-lg-offset-2">
чё с отступом стало

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +      <div class="card-container">
а зачем

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +              <a class="footer-link" href="#">
да что с отступами творится

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +          <nav class="footer-list2">
зачем этот лист2?

2017-06-16 21:44 UTC, evgenyrodionov commented on src/complexes.html
> +  </footer>
да что с отступами-то

2017-06-16 21:44 UTC, evgenyrodionov commented on src/css/style.css
> +* {
убрать

2017-06-16 21:44 UTC, evgenyrodionov commented on src/css/style.css
> +* {
это очень плохой селектор

2017-06-16 21:44 UTC, evgenyrodionov commented on src/css/style.css
> +.nav a {
мы на теги не вешаем стили

2017-06-16 21:44 UTC, evgenyrodionov commented on src/css/style.css
> +.nav a {
не вешаем стили на теги потому что цсс-селектор парсится справа налево — сначала найти все ссылки с "а", а потом все "а" в "нав". Это медленно. Ну и ненадежно.

2017-06-16 21:44 UTC, evgenyrodionov commented on src/css/style.css
> +  padding-right: 11.9375rem;
что за меджик намбер

2017-06-16 21:44 UTC, evgenyrodionov commented on src/css/style.css
> +  padding-top: 2.625rem;
и тут

2017-06-17 10:36 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27252243-e2424d2c-5361-11e7-8337-0493a6746d64.png)
этот блок не как в макете

![image](https://user-images.githubusercontent.com/775692/27252244-e89ee982-5361-11e7-91e1-d59b0237330d.png)
отступы неправильные (причем вообще все)

![image](https://user-images.githubusercontent.com/775692/27252247-f3dfc4f6-5361-11e7-8080-8b88f274a23f.png)
слиплось

![image](https://user-images.githubusercontent.com/775692/27252248-fcc4b202-5361-11e7-9e7d-fe71c38b94cd.png)
вверх укатилось, похоже

2017-06-17 10:37 UTC, imevro requested changes
Макет приведи в порядок

2017-06-17 13:45 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27253391-67a1d590-537c-11e7-92bd-f76ac837bd5f.png)
кнопка не того шрифта

2017-06-17 13:47 UTC, imevro requested changes

2017-06-17 13:47 UTC, evgenyrodionov commented on src/complexes.html
> +  <title>Main</title>
давай что-ниб более осмысленное

2017-06-17 13:47 UTC, evgenyrodionov commented on src/complexes.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
это зачем? это вопрос

2017-06-17 13:47 UTC, evgenyrodionov commented on src/complexes.html
> +  <div class = "banner">
я уже тебе говорил про воробья

2017-06-17 13:47 UTC, evgenyrodionov commented on src/complexes.html
> +  <section class="center-lg">
center-lg должен быть внутри контейнера и вообще на роу. Почитай доку флекбоксгрид

2017-06-17 13:47 UTC, evgenyrodionov commented on src/complexes.html
> +                <img class="footer-arrow" src="img/arrow.svg">
куда уехало

2017-06-17 13:47 UTC, evgenyrodionov commented on src/css/style.css
> +﻿:root {
зачем

2017-06-17 13:47 UTC, evgenyrodionov commented on src/css/style.css
> +  font-family: 'Fira Sans', sans-serif;
это вешается на бади

2017-06-17 18:13 UTC, imevro requested changes

2017-06-17 18:13 UTC, evgenyrodionov commented on src/css/style.css
> +  margin: 0em;
зачем это, объясни?

2017-06-17 18:32 UTC, VLanc commented on src/css/style.css
> +  margin: 0em;
чтобы задать шрифт и убрать марджины по всей странице, не?

2017-06-17 19:07 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27255585-360f0002-53a9-11e7-802b-d588727a1122.png)
![image](https://user-images.githubusercontent.com/775692/27255589-41ddcb34-53a9-11e7-8309-c0742e4a3404.png)
![image](https://user-images.githubusercontent.com/775692/27255592-4b33d16a-53a9-11e7-9e9b-c0a3c50e9d0f.png)

2017-06-17 19:07 UTC, imevro requested changes
дизайн-дизайнчик

2017-06-18 00:41 UTC, imevro requested changes

2017-06-18 00:41 UTC, evgenyrodionov commented on src/complexes.html
> +  <header class ="header-main">
ты

2017-06-18 00:41 UTC, evgenyrodionov commented on src/complexes.html
> +        <img class ="header-logo" src="img/compass-logo.svg" alt="compass-logo">
издеваешься

2017-06-18 00:41 UTC, evgenyrodionov commented on src/complexes.html
> +  <div class = "banner">
да?

2017-06-18 00:41 UTC, evgenyrodionov commented on src/complexes.html
> +    <img class ="banner-logo" src="img/compass-development-logo.svg" alt="compass-development-logo">
специально это делаешь?

2017-06-18 12:08 UTC, imevro requested changes

2017-06-18 12:08 UTC, evgenyrodionov commented on src/css/style.css
>  .footer-list>.footer-link:last-child {
так, это хуевый селектор

2017-06-18 12:08 UTC, evgenyrodionov commented on src/css/style.css
>  .footer-list>.footer-link:last-child {
я про >

2017-06-18 21:42 UTC, merged

2017-06-18 21:42 UTC, evgenyrodionov commented
гит фетч --олл, гит пулл --ребейз